# Generated by Django 6.0.5 on 2026-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('or', 'Odia'), ('as', 'Assamese')], default='en', max_length=5),
        ),
    ]
