# Generated by Django 6.0.7 on 2026-07-09 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligibility_result', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('needs_review', 'Needs Manual Review')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('checked_date', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='schemes.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eligibility_eligibilitycheck',
                'ordering': ['-checked_date'],
                'indexes': [models.Index(fields=['eligibility_result'], name='eligibility_eligibi_0d3b1d_idx')],
            },
        ),
    ]
