# Generated by Django 6.0.7 on 2026-07-09 11:06

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('income_certificate', 'Income Certificate'), ('caste_certificate', 'Caste Certificate'), ('residence_proof', 'Residence Proof'), ('bank_passbook', 'Bank Passbook'), ('ration_card', 'Ration Card'), ('photo', 'Passport Photo'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, help_text='Optional link to the application this document supports.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['verification_status'], name='documents_d_verific_9ea278_idx')],
            },
        ),
    ]
