# Generated by Django 6.0.7 on 2026-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='AI or admin rejection reason if verification fails.', null=True),
        ),
    ]
