# Generated by Django 6.0.7 on 2026-07-09 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Scheme Name')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('required_documents', models.TextField(blank=True, help_text='Comma or newline separated list of documents needed to apply.')),
                ('official_link', models.URLField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'schemes_scheme',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='schemes_sch_categor_cff10f_idx'), models.Index(fields=['department'], name='schemes_sch_departm_42dbbc_idx')],
            },
        ),
    ]
