# Generated by Django 6.0.7 on 2026-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='bpl_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='caste_categories',
            field=models.CharField(blank=True, help_text='Comma-separated eligible categories (e.g., general,sc,st,obc,ews)', max_length=255),
        ),
        migrations.AddField(
            model_name='scheme',
            name='gender_limit',
            field=models.CharField(blank=True, help_text='male, female, other, or blank for all', max_length=20),
        ),
        migrations.AddField(
            model_name='scheme',
            name='land_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='max_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='state',
            field=models.CharField(default='all', help_text='State code (e.g., ap, ts, tn, all)', max_length=50),
        ),
    ]
