# Generated by Django 6.0.7 on 2026-07-13

from django.db import migrations

def fix_poncare_formatting(apps, schema_editor):
    Scheme = apps.get_model('schemes', 'Scheme')
    try:
        # Find the PONCARE scheme
        scheme = Scheme.objects.get(name__icontains="poncare")
        
        # Format the required documents list properly as comma-separated values
        scheme.required_documents = (
            "Aadhaar Card, "
            "Birth Certificate / Age Proof, "
            "Residence-cum-Nativity Certificate, "
            "Recent Passport-Size Photograph, "
            "Bank Passbook"
        )
        scheme.save()
    except:
        pass

def reverse_fix(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_scheme_how_to_apply'),
    ]

    operations = [
        migrations.RunPython(fix_poncare_formatting, reverse_code=reverse_fix),
    ]
