# Generated by Django 6.0.7 on 2026-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_account_number_profile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
